### ISSUE TITLE
does this module support setup password of x-pack built-in user such as elastic super user?

### ISSUE THREAD

**Issue by wangqinghuan** [elastic/puppet-elasticsearch#1006]
x-pack build in serveral users such as elastic, kibana,logstash.. and provide a command tools setup-password to setup built-in user password. But setup-command in x-pack installed by puppet-elasticsearch does not work with error 'es_config_path must be set'. Does puppet-elasticsearch has support to employ setup-password command?

**Comment by tylerjl** [comment]
The `elasticsearch-setup-passwords` utility is designed to be run ad-hoc by operators, so there's not a particular Puppet resource that this module provides to use the utility. However, you can continue to use the utility from the shell if you set `ES_PATH_CONF` appropriately when invoking the command. It is removed from the default Elasticsearch configurations in order to properly support multiple instances. For example:

```
ES_PATH_CONF=/etc/elasticsearch /usr/share/elasticsearch/bin/elasticsearch-setup-passwords ...
```

Does that answer your question?

**Comment by wangqinghuan** [comment]
Okay, thank you @tylerjl
