### ISSUE TITLE
init_defaults doesn't work properly with java opts values

### ISSUE THREAD

**Issue by dblessing** [elastic/puppet-elasticsearch#105]
One of the configs that can be set in the elasticsearch defaults file is ES_JAVA_OPTS. There are 2 issues in this module that cause settings this variable to fail.

First, I think there need to be quotes around the value in the set command - i.e. "set ES_JAVA_OPTS "values here". Right now there are no quotes.

Second, even with quotes it appears the shellvars lens doesn't like the java opts value - probably because there are spaces in it. Being able to set java_opts in this file is critical for us so we can add some GC and JMX options.

**Comment by elisiano** [comment]
I'm seeing this with the latest version of the module (from the forge - 0.15.0).
Since we cannot specify ES_HEAP_SIZE anymore with elasticsearch 5, I set ES_JAVA_OPTS but when I try with the space (`ES_JAVA_OPTS="-Xms8g -Xmx8g"`) then augeasproviders_shellvar fails.

When I try with just `ES_JAVA_OPTS="-Xmx8g"` it works fine.

Anyone aware of a workaround?
