### ISSUE TITLE
Plugins, instances and configs

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#226]
At the moment plugins are shared between instances.
This allows us to install multiple instances of Elasticsearch and just have a single copy of the plugin on the system.
This is done because i always had the assumption that one would use the same plugins for each instance on the same server.
Obviously assumptions can be wrong so i want to start this discussion.
Also we are now getting plugins that have separate config files then the elasticsearch.yml file.
Are those files something we want to shared between instances?

So the core of this question is:

1. Do we want plugins to be shared or separate per instance
2. Do we want plugin specific config files to be shared or separated per instance

**Comment by jordansissel** [comment]
@c-a-m @uboness Any thoughts here?

**Comment by c-a-m** [comment]
The files we use in shield are users, user-roles, roles, syskey, role_mappings.  We want them all to be the same on all nodes.  But... the keystore we needs to be different.  They will have to be configured per node.

**Comment by uboness** [comment]
@electrical this sounds scary (sharing the plugins on all instances)... I'd do that only if you also share the elasticsearch jars between all instance (not sure how the puppet is managing the multiple instances). If each ES instance has its own ES jar, then I'd also have each instance have its plugin jar (when each instance has its own es jar, it means that instances can be of different versions, and then you might need different plugin versions for compatibility reasons).

As @c-a-m mentioned above, the main file that is different between the instances is the keystore. the file path is configurable in the elasticsearch.yml, and therefore can also be overridden with cmd line arguments (`--shield.ssl.keystore.path`)

**Comment by uboness** [comment]
what about scenarios where you want multiple instances belonging to different clusters on the same machine (just wondering)... does that mean ppl won't be able to use our puppet modules?

**Comment by electrical** [comment]
@uboness The Puppet module does the following with multi instances:

1. Install a single package via rpm/deb
2. Create separate config files and init scripts per instance.

This ensures that all the instances have the same version of ES running but they can be part of different clusters depending on the configuration.
This is the only reason its possible to shared the plugins between instances.

**Comment by uboness** [comment]
ok, got it... so effectively we're already sharing the es jars between the different instances. In that case (as I stated above) it makes sense to share the plugin jars as well. that said, since you already have different configuration for each instance, then I'd just follow the same pattern for plugins and have each instance have its own plugin configs as well.

**Comment by mikey-** [comment]
do you think there should be a default value for instances? maybe 'elasticsearch'? for those who only run one instance?

**Comment by electrical** [comment]
@mikey- having a 'magical' instance being setup independent of other defined instances is something that people won't expect, that's why I've decided not to do that.
There is also no decent way to detect if someone has defined an instance or not.
So by default there will be no instance running.

**Comment by mikey-** [comment]
makes perfect sense. Thanks! <3

**Comment by mikey-** [comment]
Actually, I have to ask, what would the instance name be for `class { 'elasticsearch' : }` ? or is that what you meant by "having a 'magical' instance being setup independent of other defined instances is something that people won't expect, that's why I've decided not to do that."? If it that's what you meant, I would have totally disagree and say that's exactly what people expect (also that's what the README implies). 

Say I have one instance and I didn't pass in a value for $instances when defining the class (like in the example above); will an instance will still be created as well? and will it [default to using $name for the service](https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/instance.pp#L296)? Or do I have to explicitly define an instance and name it whatever I want. 

If an instance is created when the no instances are specified when defining the Elasticsearch class, then couldn't you check that Elasticsearch::Service[~whatever the default value for $name is~] exists when a plugin is defined without any instances specified?

**Comment by electrical** [comment]
Very good and valid questions, It seems that i have to improve the README.
When calling the ES class with `class { 'elasticsearch': }` it does the following:
 1. Install the package
 2. Create required extra directories
 3. Remove init scripting supplied by the package install

You can either define an instance via the `$instances` variable ( hash; mainly used via hiera ) of the elasticsearch class or use the `elasticsearch::instance` define ( most commonly used )

Since the plugin installation is always called separately it will have no idea about the instances anyway and will always require the names of the instances to be given to the plugin define.

Hope this answers some of your questions?

**Comment by mikey-** [comment]
Yep yep yep super clear now (: Thanks again ^_^

**Comment by damnski** [comment]
Howdy, 

The "instances" documentation needs to be plural in the example of the README.md (regarding hash merging, 'mainly via hiera').  I got jammed up on this until I reviewed the manifest/init.pp code itself.  I was following the README.md using `elasticsearch::instance` in the hiera/YAML, but you need to use `elasticsearch::instances`.

Can you please change the README.md https://github.com/elastic/puppet-elasticsearch#main-and-instance-configurations?

Thanks.

**Comment by bilsch** [comment]
not sure if this is a separate issue or related. Using the plugins with ensure => latest does not reliably upgrade when elastic has changed. Is there some magic to determine the latest version of a given plugin for the version of elasticsearch running?

```
[2015-12-21 10:23:43,910][WARN ][bootstrap                ] If you are logged in interactively, you will have to re-login for the new limits to take effect.
[2015-12-21 10:23:44,055][INFO ][node                     ] [mitessec3-sec] version[2.1.1], pid[21757], build[40e2c53/2015-12-15T13:05:55Z]
[2015-12-21 10:23:44,055][INFO ][node                     ] [mitessec3-sec] initializing ...
[2015-12-21 10:23:44,064][ERROR][bootstrap                ] Exception
java.lang.IllegalArgumentException: Plugin [license] is incompatible with Elasticsearch [2.1.1]. Was designed for version [2.1.0]
        at org.elasticsearch.plugins.PluginInfo.readFromProperties(PluginInfo.java:117)
        at org.elasticsearch.plugins.PluginsService.getPluginBundles(PluginsService.java:302)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:108)
        at org.elasticsearch.node.Node.<init>(Node.java:146)
        at org.elasticsearch.node.Node.<init>(Node.java:128)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

The previous version was 2.0. The rpm package upgraded but the service would not start due to license ( and then shield and others possibly - I nuked all ) prevented it from functioning.

**Comment by electrical** [comment]
@bilsch can you show me the puppet part for it?

**Comment by bilsch** [comment]
@electrical just updated my comment with the hiera. is that what you were looking for? I'm just using the magical hiera plugins hash merge

**Comment by electrical** [comment]
Ahh okay.
the license, shield and watcher have shorter names these days instead of the long names.
If you remove the 'elasticsearch' and 'latest' parts it should upgrade nicely.
