### ISSUE TITLE
Managed repository proxy support

### ISSUE THREAD

**Issue by gonrada** [elastic/puppet-elasticsearch#274]
Would it be possible to have the module support setting the yumrepo proxy setttings when installing the repo?  The yumrepo type does support proxy setttings. [docs.puppetlabs.com](https://docs.puppetlabs.com/references/latest/type.html#yumrepo)

Thanks

**Comment by electrical** [comment]
Thanks for the request. I'll have a further look at this next week as I'll be traveling this week.

**Comment by electrical** [comment]
Sorry for the delay on this. I've been looking at all the repo management parts and it seems that its only easy to implement for yumrepo but not for apt or zypprepo.
Because of this I'm slightly reluctant to implement this.

the puppetlabs-apt module only allows for global proxy and zypprepo none at all directly ( possibly in the config it self )
I also see that yum supports a global proxy config which can be used.

**Comment by electrical** [comment]
Closing this as no feedback has been given.
