### ISSUE TITLE
When setting to absent, make sure we clean everything out

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#305]
Follow up from https://github.com/elastic/puppet-elasticsearch/issues/227
At the moment we don't clean enough yet and should look into this.

**Comment by tylerjl** [comment]
Closing as the original `ensure => absent` issue regarding repo version downgrading will be resolved in #652, and there's not a clear ask regarding `ensure => absent` as it relates to defined types since, by definition, we don't know the define/instance names to remove unless `absent` is set on the instance (as opposed to a global `absent` on the class).
