### ISSUE TITLE
Plugin fails after initial install

### ISSUE THREAD

**Issue by jmkgreen** [elastic/puppet-elasticsearch#311]
elasticsearch::plugin{'royrusso/elasticsearch-HQ':
      module_dir => 'hq',
      instances  => 'es-01'
    }

Works fine the first run. After that we get errors:

    Notice: /Stage[main]/Main/Node[elasticsearch..int.example.com]/Elasticsearch::Plugin[royrusso/elasticsearch-HQ]/Exec[install_plugin_royrusso/elasticsearch-HQ]/returns: -> Installing royrusso/elasticsearch-HQ...
    Notice: /Stage[main]/Main/Node[elasticsearch..int.example.com]/Elasticsearch::Plugin[royrusso/elasticsearch-HQ]/Exec[install_plugin_royrusso/elasticsearch-HQ]/returns: Failed to install royrusso/elasticsearch-HQ, reason: plugin directory /usr/share/elasticsearch/plugins/HQ already exists. To update the plugin, uninstall it first using --remove royrusso/elasticsearch-HQ command
    Error: /usr/share/elasticsearch/bin/plugin -install royrusso/elasticsearch-HQ returned 74 instead of one of [0]
    Error: /Stage[main]/Main/Node[elasticsearch..int.example.com]/Elasticsearch::Plugin[royrusso/elasticsearch-HQ]/Exec[install_plugin_royrusso/elasticsearch-HQ]/returns: change from notrun to 0 failed: /usr/share/elasticsearch/bin/plugin -install royrusso/elasticsearch-HQ returned 74 instead of one of [0]
   

Did I do something wrong?

**Comment by electrical** [comment]
I did a quick check and it seems that the module_dir should be 'HQ'.
I'm very sorry for the lack of documentation around it ( still trying to improve that )

The module_dir setting is the directory where the plugin is installed in so we can validate if the plugin is actually installed or not. ( by checking if the directory exists )
Since the directory is in capital letters and you supplied lowercase it tries to re-install it again.

I'm still trying to find a better way to validate if a plugin is installed but no luck so far.

Hope this helps.

**Comment by jmkgreen** [comment]
I thought that `module_dir` was supposed to tell puppet where to install the module, not where the module installs itself into :-)

**Comment by electrical** [comment]
Sorry for the confusion about it, i really need to improve the documentation around it and find something to improve it.

**Comment by jmkgreen** [comment]
Just sent a pull request to at least get the field clarified.
