### ISSUE TITLE
logrotate support needed

### ISSUE THREAD

**Issue by blalor** [elastic/puppet-elasticsearch#34]
`/var/log/elasticsearch/${cluster.name}*.log` needs to be rotated via logrotate.

**Comment by laurikari** [comment]
I know this issue is long closed, but just ran into this three years later.  

Due to a flurry of errors being logged, one of the servers in our cluster had generated several gigabytes of logs, nearly filling the disk.  Now, 3 months later, the disk actually did run out of space, resulting in a failure of the node.  Fortunately, the cluster survived, and the node recovered after freeing up space.

My question is, where should I take this up?  Who maintains the dpkg packages?  The default behaviour should be that log files get rotated.  A package which doesn't do that is basically broken.

**Comment by tylerjl** [comment]
Sorry about the rotation issues, @laurikari. Like electrical mentioned, the module does have logging.yml management in it now, although rotation in the sense of a file for `logrotate.d` isn't.

The [upstream elasticsearch repo](https://github.com/elastic/elasticsearch) is the place to discuss packaging (look under the `:Packaging` label for related issues). Based upon what I've read to get some context, the log4j version shipped with ES can't rotate/delete old log files. If you want to push for some logrotate files to be shipped with dev/rpm packages, that'd be a place to file issues.

If the need is intense enough, we could probably start handling rotation files by dropping a config into `logrotate.d`, though I'm not familiar with how the log file timestamps may change between versions of ES.

**Comment by laurikari** [comment]
Thanks @tylerjl!  I'll take this upstream.
