### ISSUE TITLE
apt_key warning

### ISSUE THREAD

**Issue by arkadicolson** [elastic/puppet-elasticsearch#445]
Warning: /Apt_key[Add key: D88E42B4 from Apt::Source elasticsearch]: The id should be a full fingerprint (40 characters), see README.

Change D88E42B4 into 46095ACC8548582C1A2699A9D27D666CD88E42B4 in the repo.pp

Thx!

**Comment by electrical** [comment]
Hi,

This is a known issue indeed. This is caused by using the short key which is required for some of the older puppet Enterprise versions i'm supporting which are pinned using older apt module versions.
As soon as i can drop support for those i'll update it, but figured a warning is better then dropping support for things :-)
