### ISSUE TITLE
puppetlabs-apt dependency when using puppetlabs-rabbitmq

### ISSUE THREAD

**Issue by driegel** [elastic/puppet-elasticsearch#453]
This is not really a bug, however, I spent some amount of time finding this. Please see my questions at the bottom.

I am using Puppet to manage Elasticsearch and RabbitMQ. So I am using
```
puppet module install puppetlabs-rabbitmq
puppet module install elasticsearch-elasticsearch
```

For the elasticsearch module, version 0.9.6 will be installed (instead of version 0.9.9) and normal upgrade will fail because of dependencies.

Dependency reason from metadata.json
```
puppetlabs-rabbitmq
{"name":"puppetlabs/apt","version_requirement":">=1.8.0 <3.0.0"}

elasticsearch-elasticsearch
{"name":"puppetlabs/apt","version_requirement":">= 1.4.0 < 2.0.0"}
```
The RabbitMQ module would install puppetlabs-apt (v2.1.0). That is why version 0.9.6 of the elasticsearch module is installed since it doesn't have the dependency yet. Changing the order of module installation would be one way for me to resolve this, because puppetlabs-apt (v1.8.0) would be used.

Finally, upgraded 
```
puppet module upgrade --force elasticsearch-elasticsearch
```
and everything seems to run fine even with puppetlabs-apt (v2.1.0).

Questions
-------------

1. Can you please list the requirement in the docs?
2. Could you test if the elasticsearch module would properly run with newer versions of the puppetlabs-apt module?

Thank you so much!

**Comment by electrical** [comment]
Hi @driegel thank you very much for the extensive write-up of the issue.
The limitations of the ES puppet module regarding the apt module dependency are indeed an issue that I would very much like to have solved.

There have been several different PR's for solving different parts which made me feel that not everything might be solved with them.
The other issue is that the ES module has to remain compatible with older apt module versions since older PE versions are pinned using certain module versions which requires extra testing.

From what I've been able to manually test show that apt 2.1.0 is compatible with 1.8.0 and should cause no issues.
The only 'fear' i have is that people might have 2.0.x installed which will not work and the dependencies won't allow me to specify multiple ranges for the same dependency.

I've been thinking of the following solution;

1. change the apt version dependency to include anything below 3.0.0
2. Document that 2.0.x will not work with this module with a link to the changelog for 2.1.0 for the compat changes.
3. The key length error will remain for now since older apt versions on PE will fail with longer keys.

What do you think of this plan?

**Comment by bastelfreak** [comment]
What about dropping support for older PE versions and only support the latest APT module version?

**Comment by philipwigg** [comment]
You could always not depend on the apt module at all and just copy the classes you need from the apt module into your own module.

**Comment by electrical** [comment]
@philipwigg that would require to much copying and keeping track of changes / fixes. that is something i want to avoid :-)

**Comment by driegel** [comment]
Hi @electrical,

well, you are the expert ;-)

I feel that your points 1 & 2 would work. I am only using the puppet modules to kick-start Elasticsearch, Logstash, Kibana, RabbitMQ and Curator so that I am having a working system within minutes.

**Comment by maxstepanov** [comment]
+1
yeah, this is the only module out of 50 i'm using that still haven't updated the version constraint for apt.
Most of them have apt ">=1.8.0 <3.0.0" and work just fine.

**Comment by philipwigg** [comment]
:+1:  Updating the dependencies and documenting that it doesn't work with 2.0.0 seems like the least worst option.

**Comment by ilyash-p** [comment]
+1

**Comment by madAndroid** [comment]
Totally agree with @maxstepanov - I've forked this module just so that I can set the apt dependency to:
```
    {
      "name": "puppetlabs/apt",
      "version_requirement": ">= 1.4.0 < 3.0.0"
    },
```

**Comment by electrical** [comment]
Hi guys,

Done some more testing and it works fine indeed.
There are several PR's open that indicate there is more functionality required ( regarding apt-get update command execution ) which I am also looking into.

I expect the next release to be compat with pl-apt 2.1.x and higher.

**Comment by madAndroid** [comment]
Awesome, cheers @electrical :)

**Comment by driegel** [comment]
@electrical Thank you so much for looking into that.

I guess you can close the issue once everything is done on your side, can't you?
Thanks again!

**Comment by electrical** [comment]
@driegel yeah, i will close this issue once its solved.

**Comment by electrical** [comment]
Has been fixed in the master branch. Will be doing a release this week.

**Comment by maxstepanov** [comment]
No it has not. Not on github.

**Comment by electrical** [comment]
Sorry, just bumped the version dependency in the master branch. forgot to do that part.
Release will be done this week after some more testing.
