### ISSUE TITLE
PL-apt 2.x support ( feedback requested )

### ISSUE THREAD

**Issue by electrical** [elastic/puppet-elasticsearch#461]
Hi all,

I've seen several different solutions so far to implement PL-apt 2.x support and its very confusing which one is the best solution.

# https://github.com/elastic/puppet-elasticsearch/pull/452
In repo.pp file
```
Class['apt::update'] -> Package[$elasticsearch::package_name]
```

# https://github.com/elastic/puppet-elasticsearch/pull/448
On package resource:
```
require => Class['apt::update']
```

I would like to try and keep the apt parts confined to the repo.pp so it has the least possible impact on people if they don't use the repo management and have their own thing in place.
Also in the current form in the module i already force that the repo management happens before the package install it self at https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/init.pp#L376-L378
And the repo management by the apt modules notifies the apt-get update part at https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/setting.pp#L50

I would like to have some feedback on which solution people think its best.

**Comment by electrical** [comment]
@driegel @madAndroid @maxstepanov @philipwigg @pcfens @Pryz @br0ch0n @s12v @liamjbennett  @Tombar
Would love your feedback on this. Thank you!

**Comment by pcfens** [comment]
Since I wrote #452, I figured a little explanaition of why I added [new relationship line](https://github.com/elastic/puppet-elasticsearch/pull/452/files#diff-bdd716adf278285c0d7f4a1651befad5R36) might help a bit. If I understand correctly, the resulting compiled catalog is the same with both approaches - but I tend to like the approach that keeps all things repo in `repo.pp`. What follows is a little dense, but I hope helps.

If I'm reading the documentation on [containment](https://docs.puppetlabs.com/puppet/latest/reference/lang_containment.html#containing-classes) correctly, classes declared inside of classes (like `apt::update` inside of `apt`) don't follow the same ordering restrictions  as the class doing the declaration. This was considered a [bug](http://projects.puppetlabs.com/issues/8040) that was [fixed](https://github.com/puppetlabs/puppet/pull/1878) by adding the `contain` function.

In this case, we ensure that the `Apt::Source['elasticsearch']` definition is handled before the package is installed, but that doesn't ensure that `Class[apt::update]` (and more specifically the contained [`Exec['apt_update']`](https://github.com/puppetlabs/puppetlabs-apt/blob/master/manifests/update.pp#L53-L60)) runs before the package.

In the case of `apt`, the `apt::update` class should come after the `apt::source` resources and before packages, but there's no safe way for the `puppetlabs/apt` module to set this up using `contain`, or adding the relationship to their module. The authors of the `apt` module [recommend](https://github.com/puppetlabs/puppetlabs-apt#adding-new-sources-or-ppas) setting the `Class['apt::update'] -> Package[...]` relationship, at least for use cases where the repository and dependent package should be added in a single puppet run.

**Comment by liamjbennett** [comment]
I have to +1 on the repo.pp method because of both class containment and also for context containment benefits you mentioned. 

It's also how we manage apt dependencies internally and how I expect many others do to.

**Comment by s12v** [comment]
+1 on repo.pp as well

**Comment by Tombar** [comment]
+1  on #452

**Comment by electrical** [comment]
Thank you for the feedback guys and @pcfens thank you for the extended write up.

Did anyone test the module with others when adding `Class['apt::update'] -> Package[$elasticsearch::package_name]` to the repo part to validate the package stuff works like expected?

Thanks!

**Comment by farvour** [comment]
:+1: on #452

**Comment by electrical** [comment]
#452 has been merged and bumping the version in metadata file soon and doing a release this week.
