### ISSUE TITLE
Templates fail when network.bind_host doesn't include loopback

### ISSUE THREAD

**Issue by gingerwizard** [elastic/puppet-elasticsearch#540]
The templates are applied using localhost as the address.  Prior to 1.7 this worked. With changes in 2.0, the user is encouraged to specify the bind and publish host.  This is typically set to the eth interface and a specific IP.  This prevents ES from receiving queries on the loopback interface.  Template application therefore fails.

**Comment by electrical** [comment]
Exposing a host & Port option would be sufficient with defaulting to fact ipaddress ?

**Comment by driegel** [comment]
@electrical  No, it won't be sufficient to use the fact $ipaddress. My systems have several IP addresses:

public IPv4
(public IPv6)
cluster internal IPv6
localhost - depending on Linux distribution (CentOS 7 or Ubuntu 15.10) it points to IPv6 and/or IPv4!
::1
127.0.0.1

In In the Elasticsearch config it is possible to set 'http.bind' to multiple IP addresses and I usually use 
\_local:ipv6\_ or the cluster internal IPv6 address. The fact $ipaddress would represent the public IPv4 address.

The save way is to specify the host for plugin installation:
```
elasticsearch::template{'custom-marvel':
        content=> template('template-file.erb'),
        ensure => 'present',
        host => 'localhost6',
        #host => 'ip6-localhost',
}
```
or some other IP address.

**Comment by electrical** [comment]
@driegel Thank you very much for your insight on this. Its very important to have these kind of details.
What would be to you a sane default for the host value which still can be overwritten of course.

**Comment by driegel** [comment]
@electrical I feel, the proper way would be: find one IP address and port of (any) Elasticsearch instance on the system as a custom fact. That would be in elasticsearch::instance.

**Comment by tylerjl** [comment]
I played around with this a little bit, and I think the current state is ok given that `elasticsearch::template` has parameters for `host` and `port`. While having the resource "autodiscover" a listening IP/port combination to talk to is nice in theory, there's even more potential for chaos down that route since 1) the resource doesn't know which instance to talk to on multi-instance machines (unless an additional parameter is given - in which case, just use `host`/`port` anyway), 2) custom facts can't be injected after the puppet run has begun and thus this doesn't work on a new installation, and 3) users should have a fair bit of flexibility on their side in their puppet manifest with pre-existing `$ipaddress_{interface}` facts if there's a need for flexibility when defining `host`.

I'll close this in a couple days unless someone has objections.

**Comment by driegel** [comment]
@tylerjl I would agree with you on this. The default behavior is documented, go ahead and close this issue.

**HOWEVER**, I wonder if it would be possible to have the host/port default documentation earlier in the template section, because it is so easy to miss it at the bottom. Maybe we could have something like this:
```
elasticsearch::template { 'templatename':
  host => 'localhost',
  port => 9200,
  content => '{"template":"*","settings":{"number_of_replicas":0}}'
}
# By default it uses localhost:9200 as host. you can change this with the host and port variables.
```

Thanks!

**Comment by tylerjl** [comment]
Thanks for the input, I've added clearer documentation in 338e5c0. Cheers! 👍
