### ISSUE TITLE
instance.pp fails to remove scripts directory

### ISSUE THREAD

**Issue by ravinaik1312** [elastic/puppet-elasticsearch#611]
I have a wrapper that wraps this elasticsearch puppet module. My module then calls the classes, functions of this module. Facing an issue where I am calling elasticsearch::instance, getting the following error

```
Elasticsearch::Instance[centos-64-x64]/File[/etc/elasticsearch/centos-64-x64/scripts]: Not removing directory; use 'force' to override
Error: Could not remove existing file
```

looking at [the code](https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/instance.pp#L284) and looking up what that error means and [documentation](https://docs.puppet.com/puppet/latest/reference/type.html#file-attribute-ensure) around the type involved, I think we should be adding the attribute force => true to it to get around the issue. 

What do you guys think?

Thanks!

**Comment by tylerjl** [comment]
It sounds like your wrapper may be creating the `scripts` directory for some reason outside the scope of this module. `elasticsearch::instance` then sees the directory already there and doesn't remove it.

I'd prefer to avoid adding `force` to the `file { ensure => link }` resource in `elasticsearch::instance` since there's the potential for data loss here if someone is storing scripts in the directory for some reason and puppet decides to do a `rm -rf` on the directory without showing a warning like this.

Since you're already using a wrapper around the module, would prefacing the manual call to `elasticsearch::instance` with a `file` resource work for you? Something like

```
file { "${elasticsearch::configdir}/centos-64-x64/scripts" :
  ensure => absent,
  force => true,
} -> elasticsearch::instance { 'centos-64-x64' :
  ...
}
```

Maybe?

If that doesn't work I'm open to something like a PR that exposes a `force` parameter on the `elasticsearch::instance` type if you'd prefer that.

**Comment by ravinaik1312** [comment]
> I'd prefer to avoid adding force to the file { ensure => link } resource in elasticsearch::instance since there's the potential for data loss here if someone is storing scripts in the directory for some reason and puppet decides to do a rm -rf on the directory without showing a warning like this

This makes sense, actually. I'm going to try to find the root cause for this and try your suggestion of prefacing the call with ```force => true```

Thanks!

**Comment by ravinaik1312** [comment]
Ok, I've tried some ways around with no success. Here is the order of execution for my module

Install ES -> Install plugins from RPM(it is directly a package install, so just extract the rpm and put it in plugins directory of elasticsearch) -> Configure instance(by calling instance.pp) which triggers the service restart. 

Prefacing the call with ```file``` resource with ```force => true``` gives me error like, "Hey you have already defined the same file resource on instance.pp 284, the code I was referring about."

**Comment by philipwigg** [comment]
How about using a resource collector on that specific resource to add the ```force => true```?

Something like...

```
File <| title == '/etc/elasticsearch/centos-64-x64/scripts' |> {
	force => true
}
```

I haven't tested that though so it's syntax might be wrong. But something along those lines.

**Comment by philipwigg** [comment]
In fact, a resource reference would probably work too. See https://docs.puppet.com/puppet/latest/reference/lang_resources_advanced.html#amending-attributes-with-a-resource-reference
