### ISSUE TITLE
Certificate Chain with Shield configuration

### ISSUE THREAD

**Issue by laf-rge** [elastic/puppet-elasticsearch#634]
My root CA has an intermediate CA that signs certificates. I would like the option to configure the shield store. I can see two alternatives to perform this based on some light reading of the java_ks documentation:
1. Allow the ca certificate to be a bundle (and have the shield module process each certificate in the PEM, it currently only looks at the first one in my testing)
2. Allow an array to be passed in pointing to the PEM files for the certificates.
3. Modify the shield class to allow a already built JKS to be used.

**Comment by tylerjl** [comment]
Based upon my reading [in the java_ks provider](https://github.com/puppetlabs/puppetlabs-java_ks/blob/master/lib/puppet/provider/java_ks/keytool.rb#L15), it's already attempting to read a chain from the certificate PEM, so this may be an upstream issue if java_ks isn't reading chains correctly. Have you tried re-ording the chain of certs in the PEM file? It sounds dumb but I've seen tools consume the chain differently.

If the ordering doesn't fix anything, we could try exposing an additional parameter on `instance.pp` for [`chain`](https://github.com/puppetlabs/puppetlabs-java_ks#chain), since that seems to be the way the module likes to handle chains, though the [previously-mentioned provider](https://github.com/puppetlabs/puppetlabs-java_ks/blob/master/lib/puppet/provider/java_ks/keytool.rb#L15) is processing the chain in the same way, so that may give you similar results.

From an end-user perspective, if you'd prefer to just manage the keystore yourself, we can always modify `instance.pp` to only manage keystores if those parameters are passed and just let you manage those and the ssl config yourself.

Let me know what you think.

**Comment by laf-rge** [comment]
I tried different orders and they didn't seem to work. Looking at the debug statements it appears that only the first one was processed. This could be environment specific though.

I have configured things manually for now by creating a file resource for all instances and manually building the host specific keystore and copying them to the server manually. Then I apply the settings in a config statement. This will work for now, but if we wanted to set up instance specific keys this could get complicated.

**Comment by sasskinn12** [comment]
As i understand you want to add "many" CA certs into keystore? I suggest it doint as i do. So in module use intermidiate Ca cert and you can add toplevel certificates after that using java_ks (copy them on server as files beforoe): eg.
       java_ks { 'puppetca:keystore':
          ensure       => 'latest',
          certificate  => '/etc/pki/tls/certs/ca_certs/CA',
          target       => '/etc/elasticsearch/master0/shield/keystore.jks',
          password     => 'secret',
          trustcacerts => true,
       }
Hope it helps..
