### ISSUE TITLE
License file install

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#647]
Do you have any WIP for installing license file with install?

**Comment by tylerjl** [comment]
No plans currently.

My understanding is that the installation process is [one REST call](https://www.elastic.co/guide/en/shield/current/license-management.html#installing-license), which could be contained within a single `exec` resource. It's one of those weird cases where the resource you're defining in Puppet controls something that isn't host-specific, so every time the resource runs on `n` hosts, they're all talking to one backend (i.e., you'll definitely need `unless/onlyif` or `refreshonly`).

With that being said, if it's a feature that people feel the module should have, I can certainly add it to the roadmap. In my mind, it would be a difference between something like this:

```puppet
exec { 'install license':
  command => 'curl -XPUT -u admin -p password http://localhost:9200/_license -d @license.json',
  unless => 'curl -XGET -u admin -p password http://localhost:9200/_license'
}
```

And this:

```puppet
elasticsearch_license { 'foo' :
  license => 'file://foo',
}
```

Or something similar (you get the idea). If you or anyone has feedback whether this is something that should be prioritized, feedback is welcome.

**Comment by cdenneen** [comment]
I think it's useful and I understand it's not host specific but neither is templates in that case.

so the `@license.json` would need to be reference to the license parameter passed to the type no?
Seem like a pretty simple addition I would think based on your description above.

**Comment by tylerjl** [comment]
It would probably take the form of a custom type/provider to cleanly handle the REST/JSON aspects of the API, but yes, it would be a pretty simple resource.

I'll add the feature tag for now so we can track the request. Understand that there are some other pressing items that need to get resolved in them module (the yaml config and conflicting keys, etc.) but I'm happy to add it to the backlog.

To anyone interested in seeing this implemented, feel free to add the +1 reaction to the original comment so we can track the interest in the feature. Thanks!

**Comment by lucabelluccini** [comment]
The problem with the rest api approach is that you depend on:

- authentication params
- http enabled mandatory?
- custom http ports?

**Comment by tylerjl** [comment]
@lucabelluccini you're correct that connection parameters like HTTP basic auth, ports, and so on are required when using a REST approach. However (and do correct me if I'm wrong), installing a license is _only_ possible over the API, so it's our only option.

In addition, most of the work for exposing these connection settings exists in the existing providers this module has (see [elasticsearch_template](https://github.com/elastic/puppet-elasticsearch/blob/master/lib/puppet/type/elasticsearch_template.rb) as an example) so those connection settings are configurable. They do have be changed if an Elasticsearch installation differs from the defaults, but that's just the way it has to work since the REST API is the sole way to install a license.

**Comment by lucabelluccini** [comment]
I agree on all the points.
It would be nice to ask to the elasticsearch team to provide another license installation method.
E.g.
- periodical checks on a specific fs path containing license.json
- periodical calls to a specified url (which could be configurable) hosting license.json

**Comment by vchan2002** [comment]
I've been messing around with automating this, and I made it a multi part of process, with an exec with an onlyif condition with a shell script..., and also laying down the license json file in puppet The reason is that.....

a)  When the license plugin is installed, it automatically installs a trial license, so a simple curl of _licenses won't be a sufficient check... it needs to check whether it's an active license.
b)  I want to be able to replace the file in puppet and have it automatically updated when and if I get a new license.

Here's what I got.. don't forget the jq package resource either.....

`  
  file { '/opt/elasticsearch/license.json':
    source  => 'HOWEVER YOU WISH....',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    require => Class[elasticsearch],
    }
exec { 'install license':
    command  => 'curl -XPUT http://localhost:9200/_license -d /opt/elasticsearch/license.json',
    onlyif   => '/opt/elasticsearch/checklicense.sh',
    provider => 'shell'
    require  => [File['/opt/elasticsearch/license.json'],File['/opt/elasticsearch/checklicense.sh']]
  }
  file { '/opt/elasticsearch/checklicense.sh':
    source  => 'HOWEVER YOU WISH',
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    require => Class[elasticsearch],
}
`

Here's the content of the bash script...
`
#!/bin/bash
#Go thru conditions where we could go install a new license
eslicensestatus=$(curl -XGET http://127.0.0.1:9200/_license | jq '.license.status')
eslicensedate=$(curl -XGET http://127.0.0.1:9200/_license | jq '.license.expiry_date_in_millis')
filelicensedate=$(cat /opt/elasticsearch/license.json | jq '.license.expiry_date_in_millis')
#If it's not an active license on ES, replace it
if [[ "$eslicensestatus" != "\"active\"" ]]; then
  echo "Not active license, Installing new License"
  exit 0
#if the license file has a newer expiration date, replace it
elif [[ "$eslicensedate" -lt "$filelicensedate" ]]; then
  echo "New license installed, Installing new License"
  exit 0
#don't do anything
else
  echo "Not installing new License"
  exit 1
fi
`

**Comment by cjcenizal** [comment]
There's a related request on the forums (https://discuss.elastic.co/t/automated-install-for-x-pack-license-drop-license-json-into-the-container-filesystem/88888/4), in which a user has requested the ability to install a license via a file on the filesystem:

> We'd like to drop a license.json file directly into the config folder and have the ES node pick that up on startup. It should merge the license into the cluster state if appropriate to do so (similar to how file-based users used to work in shield). You could use the metadata on the license itself to determine if an existing license should be replaced in the cluster (based on trial vs commercial, expiration date, etc).

**Comment by tylerjl** [comment]
Documenting some footwork here for when I/someone picks this up:

- On Elasticsearch 2.x, the api endpoint is `/_license`. The response for a `GET` is of the form:
  ```
  [root@centos-7-x64 ~]# curl localhost:9200/_license
  {
    "license" : {
      "status" : "active",
      "uid" : "84b22937-aedb-4f8a-a05e-c21954bb24d4",
      "type" : "trial",
      "issue_date" : "2017-06-14T21:09:34.059Z",
      "issue_date_in_millis" : 1497474574059,
      "expiry_date" : "2017-07-14T21:09:34.059Z",
      "expiry_date_in_millis" : 1500066574059,
      "max_nodes" : 1000,
      "issued_to" : "elasticsearch",
      "issuer" : "elasticsearch"
    }
  }
  ```
- On Elasticsearch 5.x, the path has changed, and requires the correct content-type header (which this module already handles):
  ```
  [root@centos-7-x64 ~]# curl -u elastic:changeme localhost:9200/_xpack/license
  {
    "license" : {
      "status" : "active",
      "uid" : "16bb3000-5a6b-49cf-a568-a2e4f9669d60",
      "type" : "trial",
      "issue_date" : "2017-06-14T21:21:19.692Z",
      "issue_date_in_millis" : 1497475279692,
      "expiry_date" : "2017-07-14T21:21:19.692Z",
      "expiry_date_in_millis" : 1500067279692,
      "max_nodes" : 1000,
      "issued_to" : "elasticsearch",
      "issuer" : "elasticsearch",
      "start_date_in_millis" : -1
    }
  }
  ```

Thus the module should be able to use the existing parent REST native provider with the caveat that it should handle path changes between 2/5; the license structure looks the same between versions.

**Comment by BlueBeN82** [comment]
Still no update on this? Can't be that hard, i guess. This feature will most likely be requested by paying customers...

**Comment by tylerjl** [comment]
Apologies, there's lots of responsibilities outside this module as well. Pull requests are always welcome if you see an easy and effective way of implementing it! 👍
