### ISSUE TITLE
File function for elasticsearch::template - relative URLs error

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#667]
Module: 0.11.0
Puppet: 4.3.2
OS: Centos 7

```puppet
elasticsearch::template {'logstash':
  file => "file('profile/logstash.json')"
}
```

https://docs.puppet.com/puppet/latest/reference/function.html#file

```
Error: Failed to apply catalog: Parameter source failed on File[/usr/share/elasticsearch/templates_import/elasticsearch-template-logstash.json]: Cannot use relative URLs 'file('profile/logstash.json')' at /etc/puppetlabs/code/environments/logging/thirdparty/elasticsearch/manifests/template.pp:130
```

changing to:

```puppet
elasticsearch::template {'logstash':
  content => "file('profile/logstash.json')"
}
```

yields file with that as actual content (but oddly doesn't yield error with `insert_template_logstash` even though it's not valid json)

```
# more /usr/share/elasticsearch/templates_import/elasticsearch-template-logstash.json
file('profile/logstash.json')
```

Reason for using the file function is to remove the dependency on puppet fileserver, allows for cached runs. It will increase the cached catalog but that's the tradeoff.

**Comment by tylerjl** [comment]
So if I'm understanding correctly, you just want to set the template's content based upon the file contents of `logstash.json` without passing a `puppet:///` URL to `elasticsearch::template` which it'll fetch.

Based upon the assumption that you're keeping `logstash.json` on the machine you're running puppet under (or the puppetmaster) under a file path like `/path/to/puppet/modules/profile/files/logstash.json`, you should be able to use something like

```puppet
elasticsearch::template { 'logstash':
  content => file('profile/logstash.json'),
}
```

(without the quotes around `file()`). Does that change anything?

**Comment by tylerjl** [comment]
The way templates work is about to change significantly once #663 is merged, which has much more granular controls regarding API access with a ruby-native REST API client rather than plain `curl` commands. I (hope!) the improvements there will fix those types of ambiguous problems; if you want to verify that's the case, please do feel free to try it out or, alternatively, give me an example manifest and template file to add a test with to ensure your case works.

If this looks resolved but you're having those weird template problems, I'd ask that this issue be closed and the template feedback be provided in #548.
