### ISSUE TITLE
Plugin / Instance Ordering not working

### ISSUE THREAD

**Issue by edestecd** [elastic/puppet-elasticsearch#672]
https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/init.pp#L607

This ordering sequence seems to have no effect.
I get instances executed before plugins which means that sometimes the instance services are started before the plugins are installed.

I'm not sure why this ordering does not work, but I suspect the arrow placement.
```puppet
Anchor['elasticsearch::begin']
    -> Class['elasticsearch::package']
    -> Class['elasticsearch::config']
    -> Elasticsearch::Plugin <| |>
    -> Elasticsearch::Shield::Role <| |>
    -> Elasticsearch::Shield::User <| |>
    -> Elasticsearch::Instance <| |>
    -> Elasticsearch::Template <| |>
```

When I place this on my profile it works:
```puppet
Elasticsearch::Plugin<| |> -> Elasticsearch::Instance<| |>
```

I suspect we need to change this to.
```puppet
Anchor['elasticsearch::begin'] ->
Class['elasticsearch::package'] ->
Class['elasticsearch::config'] ->
Elasticsearch::Plugin <| |> ->
Elasticsearch::Shield::Role <| |> ->
Elasticsearch::Shield::User <| |> ->
Elasticsearch::Instance <| |> ->
Elasticsearch::Template <| |>
```

This syntax I have seen in several other modules, but I have never seen the former in another module.
We are using Puppet 3.x, by the way.

**Comment by tylerjl** [comment]
Thanks for the report, @edestecd. I'll look into this and add some tests to explicitly check for ordering to see if I can get failures for the behavior you're describing. 👍

**Comment by tylerjl** [comment]
I wrote some tests that confirm this is the case; it's actually an [upstream Puppet bug that's already been reported](https://tickets.puppetlabs.com/browse/PUP-1410). For users that don't use any shield users or roles, the chaining arrows won't actually get their relationships defined.

It's a little strange that you're having issues with ordering in this case since the `elasticsearch::plugin` type requires an `instances` parameter that explicitly sets `notify =>` on the indicated service(s), which implies `before =>`. Regardless, the relationship ordering in `init.pp` should be enforcing plugins before instances at a global level, so this still needs to be fixed, so I'll get it done. 👍

**Comment by edestecd** [comment]
The code you are referring to is here?
https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/plugin.pp#L98

In that case, there is no relationship between plugin and service, if ```$restart_plugin_change``` is false, which it is by default now.
Maybe we ought to just set ```require``` here instead of nothing...  That was one of my thoughts.
