### ISSUE TITLE
puppetlabs/java is not part of metadata.json

### ISSUE THREAD

**Issue by elconas** [elastic/puppet-elasticsearch#713]
* Module version: 0.13.2
* Puppet version: 3.8.7
* OS and version: Centos7

## Bug description

If ```install_java => true``` , the init.pp calls ```class { java:  ...}```, however puppetlabs/java is part of any dependency in metadata.json. It should be part of metadata.json so that automatic dependency resultions work (like librarian-puppet).

**Comment by tylerjl** [comment]
Although my initial reaction was to question whether we need the dependencies declared for optional features (people can use the module without managing Java), I agree here and think it's probably better to err on installing everything necessary for users so that there's least surprise when using the module (plus, metadata.json includes both apt and yum dependencies anyway, so it's not like we need to keep it pure for each platform). 👍  to adding this

**Comment by tylerjl** [comment]
Fixed in #716
