### ISSUE TITLE
templates missing

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#714]
* Module version: 0.13.2
* Puppet version: 4.3.2
* OS and version: CentOS 7

## Bug description

If you remove templates from `/usr/share/elasticsearch/templates_import/*.json` they do not get recreated upon a subsequent puppet run anymore.

**Comment by cdenneen** [comment]
I originally noticed this because I made a change to an existing template and it didn't overwrite.
Figuring there was something that was causing it not to "sense" a change I tried to remove file and allow puppet to write out again, no luck.

**Comment by tylerjl** [comment]
So, this is fallout from changing out templates are managed with the new native provider. Because the provider just manages json, it doesn't require files on disk anywhere.

However, I can definitely see how having a file for the template can help. This is still possible with the `source` parameter on `elasticsearch::template`, but in either case, an `elasticsearch::template` resource must be defined for the module to manage the template content.

@cdenneen, does using `source` and pointing it at a template `json` file work for your purposes, or no?

**Comment by cdenneen** [comment]
I have one from source in my files of my profile and another from hiera as
content. I updated the json and committed. The puppet run "showed" a change
but GET of that template from ES showed nothing of my change.
Therefore I needed to manually get the json and POST to API but if it
worked then on disk or not would be fine. Just didn't work.

**Comment by tylerjl** [comment]
I think I understand what you're saying. The native provider tries to determine whether the json it parses from either your source or content is the same as the json that Elasticsearch returns, but that can sometimes be difficult to compare evenly since we have to try and make a Puppet hash the same as the template json that gets returned.

When you get a chance, I'd like to see an example `elasticsearch::template` resource that exhibits this behavior so that I can reproduce it and track down what's happening - if it sees that your template differs from what's in Elasticsearch but doesn't write the updated template, we should be able to find where that's happening.

**Comment by cdenneen** [comment]
So here is the current template:
[logstash.txt](https://github.com/elastic/puppet-elasticsearch/files/509566/logstash.txt)

All I did was add line 5 ("index.routing.allocation.require.node_type" : "hot",)

So load template without that line... update your profile/files/logstash.json and watch puppet run, "say its updating the template", do a curl -s -XGET localhost:9200/_template/logstash | grep hot return nothing

**Comment by tylerjl** [comment]
So I went through this process on both 0.13.2 of the module and current master:

- Set up a CentOS 7 machine with puppet and the module
- Put together a simple manifest that installs that template without the routing allocation setting
- Puppet runs fine and is idempotent
- Change the template to add the routing line
- Re-run puppet, template is changed according to puppet output
- A manual `curl` **confirms** the template has been changed:

```shell
[root@centos-7-x64 ~]# curl -s 'localhost:9200/_template/logstash?format=yaml' | grep -C 5 hot
      number_of_shards: "6"
      index:
        routing:
          allocation:
            require:
              node_type: "hot"
        refresh_interval: "5s"
  mappings:
    _default_:
      dynamic_templates:
      - message_field:
[root@centos-7-x64 ~]#
```

The manifest looks like this:

```puppet
class { 'elasticsearch':
        java_install => true,
        manage_repo => true,
        repo_version => '2.x',
}

elasticsearch::instance { 'es-01': }

elasticsearch::template { 'logstash':
        source => 'puppet:///modules/elasticsearch/logstash.txt',
}
```

So I'm not seeing the behavior you're describing. Maybe I'm using a different ES version? (I'm using the latest from the 2.x repos, which at the time of testing is 2.4.1).

**Comment by cdenneen** [comment]
@tylerjl I'm going to close this. Not sure why, as I said past 2 days I've seen the puppet run show a POST of the updated template but when running curl it wasn't there. Today I made another change and voila it is. I can't explain it... but I'll consider this human error on my part rather than an "intermittent" issue, since I currently can't reproduce it.

For completeness sake I'd also like to correct:
```yaml
index.routing.allocation.require.node_type" : "hot",
index.refresh_interval: "5s"
```
should be
```yaml
routing.allocation.require.node_type" : "hot",
refresh_interval: "5s"
```
since "index" is implied in the settings section of a template json. (Another mistake on my part but hopefully if someone reads this, they don't make my mistake)
