### ISSUE TITLE
Issue with installing cloud-aws plugin when no proxy specified

### ISSUE THREAD

**Issue by gigi-at-zymergen** [elastic/puppet-elasticsearch#725]
- Module version: 0.14.0
- Puppet version: Puppet enterprise 2016.1.2
- OS and version: Ubuntu 14.04
## Bug description

I'm trying to do a simple installation of the cloud aws plugin using the elasticsearch 0.14.0 puppet module.  We are not specifying a `proxy_host` or `proxy_port`

```
elasticsearch::plugin { 'elasticsearch/elasticsearch-cloud-aws':
    instances => "${facts['hostname']}"
  }
```

After changing to the 0.14.0 module I get the following error running `sudo puppet agent --test`

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: no parameter named 'proxy' at /etc/puppetlabs/code/environments/INFRA_69/modules/elasticsearch/manifests/plugin.pp:161 on Elasticsearch_plugin[elasticsearch/elasticsearch-cloud-aws] at /etc/puppetlabs/code/environments/INFRA_69/modules/elasticsearch/manifests/plugin.pp:161
```

Looking at master plugin.pp:161 it seems it should be using the `$_proxy` value from the fall through conditional at https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/plugin.pp#L135

Any ideas on if I could work around this?  We were previously using the 0.10.3 release and I'll just keep working back until I can get the cloud-aws plugin to install with no proxy defined...

**Comment by tylerjl** [comment]
This can happen to Puppet occasionally when a puppet server references an updated module using pluginsync and hasn't been restarted. Can you ensure all the relevant puppet services have been restarted before attempting another run? The code should all be correct, and this has been solved similarly before.

**Comment by csubj** [comment]
Same story here when moving from 0.10.4 to 0.14.0. Restarting our puppet masters will allow for _one_ successful run. Every attempt after gets the same error.

**Comment by tylerjl** [comment]
What version of puppet and distro are you on @csubj? I've tried a few different combinations to try and get this to reproduce but can't get the error to show up for me.

Note that in moving from 0.10.x to 0.14.x, there definitely was a change to the proxy parameter in that it was renamed to `proxy` from `proxy_args`:

```

-  newparam(:proxy_args) do
+  newparam(:proxy) do
     desc 'Proxy Host'
   end

```

When puppet passes `$_proxy` into the native type, it should be passing into `proxy` rather than `proxy_args`, which is the name of the _old_ parameter. The errors seen here all point to some cache somewhere remembering the old parameter somewhere instead of the new code in the 0.14.x module, which seems accurate given a restart fixes it once.

**Comment by csubj** [comment]
- Puppet 3.7.5
- Ubuntu 14.04.2 LTS for puppet masters, 12.04.5 LTS for remote nodes

I had a talk with a colleague and he mentioned that this is probably a long standing bug with puppet; having the same module with differing function definitions in separate environments (regardless of the module's version) will cause this error - he had dealt with this not too long ago with another module. He also mentioned that its fixed with the 2016.X.X releases of puppet. 

I suppose this is what we get for running older puppet; I'll try again once we're done moving into the new puppet release.  Thanks for the help!

**Comment by gigi-at-zymergen** [comment]
I haven't gotten a chance to get back to this, and am using 0.12.0 for now, but will try the restarts and 0.14.0 and update here.  Thanks for the response.
