### ISSUE TITLE
Module support for Elasticsearch Enterprise

### ISSUE THREAD

**Issue by cdenneen** [elastic/puppet-elasticsearch#761]
Will this module or a new module provide support for Elasticsearch Cloud or Elasticsearch Enterprise?

https://www.elastic.co/cloud/enterprise

**Comment by tylerjl** [comment]
@cdenneen I'd suggest bringing up topics of discussion for features/deployment for ECE on [the Discourse forum for the product](https://discuss.elastic.co/c/cloud-enterprise) since it's a different animal than this Puppet module.

In addition to being able to hash out exactly what the user needs may be, various technical leads and PMs are there as well so everyone has better visibility into what's going on. Feel free to tag me directly on any Puppet discussions there (I'm @tylerjl there, too).
