### ISSUE TITLE
Puppet agent run gives Undefined method `shield_config' error.

### ISSUE THREAD

**Issue by wonkyto** [elastic/puppet-elasticsearch#792]
* Module version: commit b68a03380bcc776bef6458faff09050c28fa6c40
* Puppet version: puppet-server-3.6.2-4.el6_6sat.noarch, puppet-3.6.2-4.el6_6sat.noarch
* OS and version: RHEL 6.7

## Bug description

I'm currently upgrading from Elasticsearch 2.4.X -> 5.2.1

This requires to change the format of the existing (working) role definitions in the Puppet code.

Unfortunately when using the latest version from git (the latest version in Puppet Forge doesn't support x-packs roles) I get these errors relating to the shield_config as being an undefined method.

These errors occur before of my puppet code is tested/run.

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/elasticsearch_role: Could not autoload puppet/provider/elasticsearch_role/shield: undefined method `shield_config' for Puppet::Type::Elasticsearch_role::ProviderShield:Class on node XXX.XXX.XXX
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/elasticsearch_role_mapping: Could not autoload puppet/provider/elasticsearch_role_mapping/shield: undefined method `shield_config' for Puppet::Type::Elasticsearch_role_mapping::ProviderShield:Class on node XXX.XXX.XXX
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

I am calling my elasticsearch class like this:

```puppet
  class { 'elasticsearch':
    version      => $elasticsearch_version,
    java_install => true,
    java_package => 'java-1.8.0-oracle',
    require      => User['elasticsearch'],
    jvm_options  => [
      "-Xms${global_heap_size}",
      "-Xmx${global_heap_size}",
    ],
    security_plugin => 'x-pack',
  }
```

I'm not yet at the point of testing my updated role defitions (puppet fails before this)

Thanks,

David

**Comment by tylerjl** [comment]
Howdy! So, a few things:

* The current release for the module is now under `elastic-elasticsearch` on the forge instead of `elasticsearch-elasticsearch` if you want to use that official release.
* Only Puppet versions >= 3.8.0 will work, so you may want to try and get a 3.8.x version installed before you run into additional errors that arise because of that.
* Type/provider errors commonly arise after updating a module but failing to restart the puppetmaster. Have all puppet masters/agents been restarted after updating the module?

**Comment by wonkyto** [comment]
Thanks for the quick response.

I've used the latest puppet forge version ```elastic-elasticsearch``` and I get the same issue. 

I can confirm I restart the puppetmaster after deploying new code (actually restarting http, as we are using passenger).

Upgrading to puppet >= 3.8.0 is unlikely to be possible due to the greater environment constraints.

**Comment by wonkyto** [comment]
Just a side node, the README.md file says: "This module has been built on and tested against Puppet 3.2 and higher."

**Comment by tylerjl** [comment]
Gotcha, sorry about that. I'll make sure and get the documentation updated; the minimum required Puppet version is correct in `metadata.json` which is the compatibility listed on the puppet forge.

Unfortunately this module makes use of a few different traits that only versions >= 3.8.0 of puppet provide, so just be aware that you may run into additional issues if you resolve this one. As far as the issue you're describing, another thing to check would be that pluginsync is working correctly, since there are several files that the custom types and providers use.

**Comment by wonkyto** [comment]
Thanks for the feedback.

Unfortunately the amount of effort to get a new version of puppet installed is monumental. We might just have to avoid using puppet with elasticsearch until an upgrade is possible. Thanks again

**Comment by tylerjl** [comment]
No problem, sorry about the incompatibility. Good luck!
