### ISSUE TITLE
ES Instance SysConfig file is not created causing the instance to not start

### ISSUE THREAD

**Issue by hatrick1** [elastic/puppet-elasticsearch#794]
I am seeing an issue where an ES instance declared via elasticsearch::instance is failing to start because the config file in /etc/sysconfig is not present. My instance config is below, what is strange is when I remove the init_defaults config hash the file gets generated. My OS is Centos7, puppet is the latest version and I'm using the puppet code in the master branch. 

  elasticsearch::instance { 'es-b04':
    status        => 'enabled',
    config        => {
      'network.host'          => '172.16.0.59',
      'node.data'             => true,
      'bootstrap.memory_lock' => true,
      'discovery.zen.ping.unicast.hosts'   => 'elastic-b01.hft.xxx.net,elastic-b02.hft.xxx.net,
      'discovery.zen.minimum_master_nodes' => 2
    },
    init_defaults => {
      'ES_JAVA_OPTS'      => '-Xmx16g -Xms16g',
      'MAX_OPEN_FILES'    => 65535,
      'MAX_LOCKED_MEMORY' => 'unlimited',
      'MAX_MAP_COUNT'     => 262144,
      'ES_HEAP_SIZE'      => '16g'
    }
  }

**Comment by tylerjl** [comment]
This is most likely caused by the ES_JAVA_OPTS setting; augeas may fail
trying to set a value with spaces in it. Try wrapping the ES_JAVA_OPTS
value in double quotes (in addition to the single quotes you have) and see
if that resolves it (the puppet run logs may have augeas errors in them to
hint at this.)
