### ISSUE TITLE
Implement elasticsearch-keystore class to deploy secrets.

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/puppet-elasticsearch#827]
## Feature Description
Implement a new type to be able to deploy secrets via elasticsearch-keystore.

https://www.elastic.co/guide/en/elasticsearch/reference/5.4/secure-settings.html

**Comment by tylerjl** [comment]
Thanks for the issue @lucabelluccini. It looks like we can model elasticsearch secrets as a Puppet type, with the following limitations:

- Actual secret values can't be retrieved via the command-line tool, so while the _initial_ resource creation can be guaranteed to hold the specified secret value, any changes to the secret setting's value will have to be either 1) explicitly flushed with a notify to the resource or 2) always updated on every catalog run. We probably want option 1 since the tool has the invocation overhead of a java CLI app.
- The type will probably need to have the associated Elasticsearch instance specified via an `instances =>` parameter in a similar way to the `elasticsearch_plugin` type (though I think this makes sense anyway, as secure settings feel like an extension of `config =>`.

Along the lines of that last bullet point, perhaps secrets could be controlled per defined instance? For example:

```puppet
elasticsearch::instance { 'master' :
  config => { 'node.name' => 'foobar' },
  secrets => {
    'cloud.aws.access_key' => 'AKIA....',
    'cloud.aws.secret_key' => 'AKIA....',
  }
}
```

Benefits to this approach:
- A secret _cannot_ exist unless it lives alongside an instance's configdir, so this makes that assumption explicit
- Secure hash key/values can be passed to `secrets` from hiera
- We have some flexibility regarding how we actually process those secret settings within the `elasticsearch::instance` defined type (it'll probably end up looking like
  ```puppet
  elasticsearch_keystore { $name :
    values => $secrets,
  }
  ```
  Or something similar.

Thoughts?

**Comment by lucabelluccini** [comment]
Thank you for the feedback @tylerjl 

At the moment the secrets are not really instance-specific (e.g. password for bind user in LDAPS) but indeed they could be interesting for someone else deploying multiple instances belonging to different clusters on the same machine.

We could allow the setting to be cluster wise and being merged in hiera (such as config, which is specified both at elasticsearch and elasticsearch::instance level).

**Comment by tylerjl** [comment]
@lucabelluccini and any other observers, I have a branch building in CI that implements keystore support [as documented in the branch's README](https://github.com/tylerjl/puppet-elasticsearch/tree/09bbdfb4b8173b9aa74bbb5094cc4786901a0706#keystore-settings). It makes sense to me (and implements the merged config style that I agree with Luca on) so that's the direction this feature is going unless there are concerns that should be addressed.
