### ISSUE TITLE
Version pinning breaks when using alternate yum backend

### ISSUE THREAD

**Issue by calid** [elastic/puppet-elasticsearch#830]
* Module version: latest
* Puppet version: any
* OS and version: any rpm based distribution

## Bug description
Version pinning doesn't currently honor the `manage_repo` option, and always tries to use the `yum::versionlock` feature of the default yum dependency.  This breaks when wanting to manage the repo ourselves and use an alternative yum backend. 

I would like to submit a pull request that updates the package pinning logic to check `manage_repo` and only apply `yum::versionlock` when `manage_repo` is true.

**Comment by tylerjl** [comment]
The module supports managing packaging pinning and the repository as separate flags; since there can be cases in which users may have packages in a custom repo but still want to enforce package pinning - [there's a flag to enable/disable it on the top-level class (`elasticsearch::package_pin`)](https://github.com/elastic/puppet-elasticsearch/blob/f808dc4a085f4ae3c7fa604c8cfc7aae96062b95/manifests/init.pp#L742) which currently defaults to `true`. Does that parameter solve the use case here?

**Comment by calid** [comment]
I tried the `package_pin` flag but it still triggered the use of `yum::versionlock`

**Comment by calid** [comment]
it's also more predictable behavior to able to set `elasticsearch::version` with `manage_repo` set to false and have it 'just work' instead of needing to set a separate flag.

The fix is really quite trivial:
https://github.com/calid/puppet-elasticsearch/commit/2df7dd0846a99b2efaa7512f2e47d4a2ad53a8ee

**Comment by tylerjl** [comment]
The only issue with that changeset is that it breaks users who 1) manage their own repository to serve the elasticsearch packages and 2) still want to pin against those packages. Just to try out the `package_pin` flag, I tested it out and got the following on a test VM:

```
[root@centos-7-x64 ~]# cat test.pp
class { 'elasticsearch':
        manage_repo => true,
        repo_version => '5.x',
        package_pin => false,
        java_install => true,
}
elasticsearch::instance { 'es-01' : }
[root@centos-7-x64 ~]# systemctl is-active elasticsearch-es-01
active
[root@centos-7-x64 ~]# ls /etc/yum/pluginconf.d/
fastestmirror.conf  langpacks.conf  ovl.conf
[root@centos-7-x64 ~]#
```

And changing `package_pin` to `true` and setting `version`:

```
[root@centos-7-x64 ~]# cat test.pp
class { 'elasticsearch':
        manage_repo => true,
        repo_version => '5.x',
        package_pin => true,
        java_install => true,
        version => '5.4.0',
}
elasticsearch::instance { 'es-01' : }
[root@centos-7-x64 ~]# ls /etc/yum/pluginconf.d/
fastestmirror.conf  langpacks.conf  ovl.conf  versionlock.conf  versionlock.list
[root@centos-7-x64 ~]# cat /etc/yum/pluginconf.d/versionlock.list
0:elasticsearch-5.4.0-1.noarch*
[root@centos-7-x64 ~]#
```

So the flag seems to work correctly in my test setup, do you have an example setup that exhibits the behavior you're seeing so I can try and reproduce it?

**Comment by calid** [comment]
we are using a different yum module that doesn't implement `yum::versionlock`, so we get this error:

**Comment by calid** [comment]
we were under the impression the `manage_repo` flag was there to tell the elasticsearch module not to do any repo/yum operations at all, including yum::versionlock

**Comment by tylerjl** [comment]
I've confirmed that using `package_pin  => false` shouldn't cause unknown resource type errors for `yum::versionlock` if that module isn't used. Just to be clear, is there any bug here from your perspective or does the documentation just need to be made more clear?

**Comment by calid** [comment]
Yes, there is a bug.  `package_pin => false` causes unknown resource type errors for `yum::versionlock`

with the following set:

**Comment by tylerjl** [comment]
I'm confused; you mention that `package_pin => false` causes the resource type errors, but you're setting `elasticsearch::package_pin: true` in hiera, was one of those a typo?

Just to be clear, the `elasticsearch::package::pin` class _will not_ be included at all, and thus there are no resource type errors, if the `package_pin` parameter is set to false - this is explicitly checked in the `elasticsearch` class, [see this line in `init.pp`](https://github.com/elastic/puppet-elasticsearch/blob/f808dc4a085f4ae3c7fa604c8cfc7aae96062b95/manifests/init.pp#L742) where `package_pin` is checked before including `elasticsearch::package::pin` at all. I explicitly tried running a Puppet manifest with the entire `yum` module removed from disk along with `package_pin => false` and it worked without problems.

This still looks like things are functioning as expected, but if there's a bug I'm missing somewhere, I'm happy to keep digging...

**Comment by lucabelluccini** [comment]
Hello, I think the issue is similar to what we are experiencing...
We are handling the yum repository via a profile module which takes care of setting up the Yum repo mirror and encapsulates the elasticsearch one.

Version pinning is enabled.

Unfortunately, due to internal policy, at each version upgrade, we are changing both:
- yum repo baseurl (e.g. http://yumrepo/x/yum to http://yumrepo/y/yum)
- elasticsearch::version (e.g. 5.3.2 to 5.4.0)

```
  if($manage_repo) {
    yumrepo { 'elasticsearch':
      name     => 'elasticsearch',
      baseurl  => $repository,
      descr    => 'Elasticsearch yum repo mirror',
      enabled  => 1,
      gpgcheck => 0,
      notify   => Exec['refresh_elasticsearch_yumrepo'],
    }

    exec { 'refresh_elasticsearch_yumrepo':
      command     => '/usr/bin/yum clean all',
      refreshonly => true,
    }

    Exec['refresh_elasticsearch_yumrepo'] -> Anchor['elasticsearch::begin']
  }
  else
  {
    #fail("Class['profile::elasticsearch']: scenario with 'manage_repo=false' is not implemented yet.")
  }

```

Continue... Still in the profile.

```
  class { '::elasticsearch':
    datadir                 => $datadir,
    logdir                  => $logdir,
    manage_repo             => false,
    instances_hiera_merge   => true,
    config_hiera_merge      => true,
    plugins_hiera_merge     => true,
    autoupgrade             => false,
    package_pin             => true,
    elasticsearch_user      => $user,
    elasticsearch_group     => $group,
    java_install            => false,
    logging_file            => $logging_file_v,
    security_logging_source => $audit_logging_file_v,
  }

```

What happens is that on the first run after we change the hieradata:

```
Notice: /Stage[main]/Profile::Elasticsearch/Yumrepo[elasticsearch]/baseurl: baseurl changed 'http://yum......20170411/elastic-5.x/' to 'http://yum......20170515/elastic-5.x/'
Info: /Stage[main]/Profile::Elasticsearch/Yumrepo[elasticsearch]: Scheduling refresh of Exec[refresh_elasticsearch_yumrepo]
Debug: /Stage[main]/Profile::Elasticsearch/Yumrepo[elasticsearch]: The container Class[Profile::Elasticsearch] will propagate my refresh event
Debug: Exec[refresh_elasticsearch_yumrepo](provider=posix): Executing '/usr/bin/yum clean all'
Debug: Executing: '/usr/bin/yum clean all'
Notice: /Stage[main]/Profile::Elasticsearch/Exec[refresh_elasticsearch_yumrepo]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Profile::Elasticsearch/Exec[refresh_elasticsearch_yumrepo]: The container Class[Profile::Elasticsearch] will propagate my refresh event
...
...
...
Debug: Package[elasticsearch](provider=yum): Ensuring => 5.4.0-1
Debug: Package[elasticsearch](provider=yum): Detected Arch argument in package! - Moving arch to end of version string
Debug: Executing: '/bin/rpm -q elasticsearch --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Debug: Package[elasticsearch](provider=yum): Upgrading package elasticsearch from version 5.3.0-1 to 5.4.0-1
Debug: Executing: '/usr/bin/yum -d 0 -e 0 -y update elasticsearch-5.4.0-1'
Debug: Executing: '/bin/rpm -q elasticsearch --nosignature --nodigest --qf '%{NAME} %|EPOCH?{%{EPOCH}}:{0}| %{VERSION} %{RELEASE} %{ARCH}\n''
Error: Could not update: Failed to update to version 5.4.0-1, got version 5.3.0-1 instead
Error: /Stage[main]/Elasticsearch::Package/Package[elasticsearch]/ensure: change from 5.3.0-1 to 5.4.0-1 failed: Could not update: Failed to update to version 5.4.0-1, got version 5.3.0-1 instead
```

Following run works correctly.

Am I missing something?

**Comment by tylerjl** [comment]
Hey @lucabelluccini - while your issue does look similar to the original issue reported here, I think it's separate - my best guess is that your issue may have something to do with the exec call to `yum clean all`, since `rpm` can't find the updated version at all. Assuming `elasticsearch::version` is injected via hiera, the versionlock should update its config file.

I'd suggest maybe trying to mimic [the yum metadata command that this module uses to clear repo metadata](https://github.com/elastic/puppet-elasticsearch/blob/dcb6f5bd373b2ff3179ccb3fe35862c45bd0490a/manifests/repo.pp#L112) as a first debugging step - I'm not 100% sure, but I seem to remember that I ran into strange issues with `yum clean all` and explicitly calling `yum clean metadata expire-cache` worked as expected. [The behavior of `package_pin` is explicitly tested in the acceptance tests as well](https://github.com/elastic/puppet-elasticsearch/blob/dcb6f5bd373b2ff3179ccb3fe35862c45bd0490a/spec/acceptance/016_package_pin_spec.rb), so it should be working right.

**Comment by lucabelluccini** [comment]
Hello @tylerjl !

I just tested locally with:
```
exec { 'refresh_elasticsearch_yumrepo':
      command     => '/usr/bin/yum clean all && /usr/bin/yum versionlock clear',
      refreshonly => true,
    }
```

And it worked at first shot. Remember that in my case the repo is not managed by elasticsearch module but our profile.

I'll try again with your clean repo in few minutes and see if it has the same effect.

**Comment by calid** [comment]
@tylerjl yes that was a typo on my part, comment updated.

perhaps I'm misunderstanding the purpose of `package_pin`... so that simply controls whether to include package/pin.pp or not?  if `package_pin` is set to false does that mean `elasticsearch::version` simply has no effect and you need to manage the Package resource yourself?

**Comment by calid** [comment]
ok I've looked at the code a little close... so is this what I want if I want to pin the version but use our own yum module?

```
elasticsearch::version: 5.3.0
elasticsearch::package_pin: false
elasticsearch::manage_repo: false
```

**Comment by tylerjl** [comment]
@calid yes, `package_pin` just indicates whether or not the module should handle package pinning (which uses a resource in a third-party yum module). `manage_repo` will only handle managing a package repository (like a `yumrepo` - the module just uses the included `yumrepo` resource in puppet for that, so it won't conflict with any third-part yum modules).

If `package_pin` is set to false, all that does is ignores setting a yum versionlock file. You can still set `elasticsearch::version` to whatever value you need, and the module will install the indicated version, but no versionlock config file will be set - note that the versionlock config file is mostly used for safety to keep the elasticsearch package from changing outside the scope of this module, because the module will always try to keep the version set at `elasticsearch::version` installed.

So in answer to your question, if you are using your own yum module, set package_pin to false, since it needs the third-party module to do that. If you are managing your own yum repository, you can skip manage_repo as well, though usually it works fine (and doesn't use a third-party yum module). `elasticsearch::version` will install the indicated version from yum as long as it's available in a yum repo (whether one managed by this module our yourself).

@lucabelluccini if your environment doesn't necessarily need package pinning, maybe you could just set `package_pin => false`. The module will still make sure the right version is installed; it just won't try to lock it with the versionlock plugin any more (though note you'll probably need to remove the versionlock file).

What's kind of confusing is that you mentioned that in your first example case, the puppet run worked correctly the second time - does the `versionlock` resource not show any changes across the first _or_ second runs? I'd expect to see it at least once if package_pin is true and you're setting the version parameter.

**Comment by calid** [comment]
@tylerjl thank you, I'll go ahead and close the issue.  Now that I understand things I'd say it is probably worth expanding on these options in the documentation and explain their semantics in more detail.  Thanks for your patience and help!

**Comment by lucabelluccini** [comment]
@tylerjl I couldn't see any versionlock change, but I can retry today to check more in detail.
I think I'll explicitly remove the versionlock if the yum repo changes. It will anyway re-enable after update.

Thank you a lot for the support and help!

**Comment by tylerjl** [comment]
@lucabelluccini in the process of updating some module version dependencies, I ran into your exact issue in the packaging pinning acceptance tests. I'm not 100% sure that my case is exactly the issue that you were running into, but the problem was solved by making sure that my concat and stdlib modules were up to date. The root cause was that 1.x of the `yum` module uses `concat` instead of `file_line`, which uses an `Exec` in earlier versions that got lost in the dependency chain, so I'd make sure your modules are running later versions, since the behavior you noted is exactly what I observed with old versions of concat and stdlib with version 1.x of the yum module.
