### ISSUE TITLE
Boolean default is wrong in ElasticsearchRESTResource

### ISSUE THREAD

**Issue by soxwellfb** [elastic/puppet-elasticsearch#835]
I've been looking at the code in `lib/puppet_x/elastic/elasticsearch_rest_resource.rb` as a working example for a REST provider I've been writing for a different product, and have notice that `validate_tls` doesn't seem to have a valid default.

```
   extender.newparam(
      :validate_tls,
      :boolean => true,
      :parent => Puppet::Parameter::Boolean
    ) do
      desc 'Whether to verify TLS/SSL certificates.'
      defaultto true
end
```
The default value should be a symbol, I think. ie ` defaultto :true`, otherwise `p[:validate_tls].value` in the `prefetch` method in the provider returns an `undefined method 'value' for nil:NilClass` error.

It seems to be masked by the Puppet defined types always setting `validate_tls` when the type is called.

**Comment by tylerjl** [comment]
Thanks for running through the code quality of the REST types and providers; I thought I was the only one who would ever look at that low-lever provider code 😂  Bear with me on the way that stuff is laid out, I didn't find any existing REST examples to go off of.

I based the boolean parameters off of existing core Puppet type parameters with boolean values - see [this user type parameter](https://github.com/puppetlabs/puppet/blob/74c975423b57e5a6513317c635dfe05efef26f94/lib/puppet/type/user.rb#L297) as an example. Based upon how upstream Puppet does it, native ruby boolean types rather than symbols seem to be the correct approach, would you agree? If it breaks somewhere, we should definitely fix it.

Out of curiosity, I tried to manage a REST-based type with a manifest _without_ wrapping it in a Puppet defined type, and things worked as expected without any errors. Here's the example manifest that worked for me:

```puppet
class { 'elasticsearch':
	java_install => true,
	manage_repo => true,
	repo_version => '5.x',
}
elasticsearch::instance { 'es-01': }
elasticsearch_index { 'foo':
	settings => {
		'index' => {
			'number_of_replicas' => 1,
		}
	},
}
```

So leaving those parameters at their type-defined defaults didn't throw any problems. Do you have any failing examples that I could try and reproduce from?

**Comment by soxwellfb** [comment]
Hi Tyler!

Ah, I see what you mean about the upstream user type. I've gone back and re-examined my assumptions.

So, assumption one: that my code was close enough to your code, to make no difference.
```
elasticsearch_index { 'foo':
	settings => {
		'index' => {
			'number_of_replicas' => 1,
		}
	},
}
``` 
This works as expected, no errors, as you found.

My second assumption was that the boolean state made no difference. However, changing `defaultto true` to  `defaultto false` for `validate_tls` (as it is in the code I'm developing) caused this in the puppet run:

```
Error: Could not prefetch elasticsearch_index provider 'ruby': undefined method `value' for nil:NilClass
Notice: /Stage[main]/Elasticstack::Elasticsearch/Elasticsearch_index[foo]/ensure: created
Error: /Stage[main]/Elasticstack::Elasticsearch/Elasticsearch_index[foo]: Could not evaluate: Elasticsearch API responded with: index [foo/DYjzzF2NQhS-3jIXWPnsTw] already exists
```
So, looks like having a boolean parameter in Puppet (maybe just 3.8.7 and earlier?) with a default of `false` stops it from existing in the resources hash passed to `self.prefetch`. `defaultto :false` works. No idea why, but seems that's it not an issue in your code, but somewhere in Puppet.

As for the low-level provider code - I've no issues with it at all! ^_^

**Comment by tylerjl** [comment]
That is interesting - I tried passing `false` via the bare type and it works, so there's probably some Puppet bug in the 3.x series related to `defaultto :false` as you mentioned. Very weird.

Given that's an odd bug on the dead version of Puppet, feel free to close this issue (unless you feel like there's a latent bug here somewhere that should be fixed).

**Comment by soxwellfb** [comment]
No, nothing to be fixed here! Closing.
