### ISSUE TITLE
Remove java from module dependencies

### ISSUE THREAD

**Issue by edestecd** [elastic/puppet-elasticsearch#856]
Managing java is disabled by default. Therefore we should not require it in the metadata.json
I assume most manage java on their own, so they can be consistent with logstash etc...

Right now this is causing me pain, b/c you have it pinned to <2.0.0 here: https://github.com/elastic/puppet-elasticsearch/blob/master/metadata.json#L22

And we now need 2.0.1. I was going to just bump it, but it seems better to just remove this dependency... Thoughts?

**Comment by jarpy** [comment]
Personally, I'd like to see Java reduced to a note in the documentation. Something along the lines of: "You'll need Java. We recommend using puppetlabs/java and adding `require java` to your manifest."

But if a site doesn't want to use `puppetlabs/java`, we shouldn't force it on them. Maybe they have a custom module. Maybe they're experimenting with Zing. Maybe Packer puts a JVM in their base images so they don't need Puppet for that task. Maybe... you get the idea.

**Comment by tylerjl** [comment]
I had similar plans to remove package pinning from this module for 6.x since it requires pulling in a specific module to manage yum/apt pinning, and this feels similar to me. This module really [only has four lines that manage java](https://github.com/elastic/puppet-elasticsearch/blob/de599d40fbb0bd1c36a60346e40cfeeb9b2df487/manifests/init.pp#L657), and reducing the scope of what the module touches seems like a better practice. I'm +1 based upon both of your comments.

I'll plan on removing the dependency in the module metadata and references to it in the 6.x release as a breaking change (alongside other breaking changes to trim the scope of the module, like package pinning). Thanks for the feedback!

**Comment by Jarodiv** [comment]
Just ran into the same problem: We require Oracle JDK8 for another software. The latest non 2.x version of the Java manifest tries to install Java 8u51 which cannot be downloaded due to Oracles login barrier. So we now have to use a second module just for being able to download Oracle JDK8, even though that could be done with the puppetlabs-jave module (in a nerver version).

**Comment by tylerjl** [comment]
FYI since this will be a breaking change, it'll be included as a part of the 6.x release, which I already have staged in a 6.x branch. That's a ways away though, so I'll look into bumping the version soon as well to unblock people.

**Comment by tylerjl** [comment]
Updated dependency in 5.4.3, removed dependency will go out in version 6.0 of the module. 👍
