### ISSUE TITLE
Provider plugin is not functional on this host

### ISSUE THREAD

**Issue by szemlyanoy** [elastic/puppet-elasticsearch#862]
Hi,

I'm upgrading ES/2.4.3 to ES/5.5.1
Puppet module version '5.3.1'
OS: RHEL 6.8

Problem:
When applying puppet with new ES profile where v5.5 is specified I got this error on the 1st run

```
Notice: /Stage[main]/Elasticsearch::Config/File[/etc/elasticsearch/jvm.options]/owner: owner changed 'root' to 'elasticsearch'
Error: /Stage[main]/Profiles::Elasticsearch_5_5/Elasticsearch::Plugin[x-pack]/Elasticsearch_plugin[x-pack]: Provider plugin is not functional on this host
Error: /Stage[main]/Profiles::Elasticsearch_5_5/Elasticsearch::Plugin[ingest-attachment]/Elasticsearch_plugin[ingest-attachment]: Provider plugin is not functional on this host
Notice: /Stage[main]/Profiles::Elasticsearch_5_5/Elasticsearch::Plugin[x-pack]/File[/usr/share/elasticsearch/plugins/x-pack]: Dependency Elasticsearch_plugin[x-pack] has failures: true
```

The second agent's run applies catalog w/o errors...

this is how I define plugin resources
```    
elasticsearch::plugin { ['x-pack','ingest-attachment']:
      proxy_host => $_internet_proxy,
      proxy_port => $_internet_proxy_port,
      instances  => [
        'es-01',
      ],
      require    => Class['elasticsearch'],
    }
```

elasticsearch-plugin binary is already in place till the error happens
/usr/share/elasticsearch/bin/elasticsearch-plugin

Does it call wrong provider in the 1st run..?

PS when running install of ES/5.5 from scratch no issues either, only during upgrade from 2.4.3

**Comment by tylerjl** [comment]
This is kind of tricky; it seems like the problem is related to the underlying Puppet mechanics. I haven't tried to reproduce it, but I think I have an idea of what's going on: when the `elasticsearch::plugin` resource gets compiled it selects the `plugin` provider since it sees that executable on-disk, but when the resource actually runs (after the `Class['elasticsearch']` resource), it's no longer on-disk since it's been updated to the new 5.x version of the plugin utility. Normally I'd expect the provider to be selected as late/lazily as possible to ensure the provider is functional, but maybe that isn't the case.

One suggestion you may want to try would be to manually specify the plugin resource's provider:

```puppet
Elasticsearch_plugin { provider => 'elasticsearch_plugin' }

elasticsearch::plugin { ['x-pack','ingest-attachment']:
      proxy_host => $_internet_proxy,
      proxy_port => $_internet_proxy_port,
      instances  => [
        'es-01',
      ],
      require    => Class['elasticsearch'],
}
```

And see if that makes a difference (I'm not 100% sure on that syntax, but the idea is to force that type to use the 5.x provider by default). Does that make a difference?

**Comment by szemlyanoy** [comment]
brilliant! it helped, thanks
