### ISSUE TITLE
Systemd Template ExecStartPre Executable Removed in Upstream 6.x

### ISSUE THREAD

**Issue by dfwarden** [elastic/puppet-elasticsearch#875]
This probably relates to #776.

It appears elasticsearch-systemd-pre-exec was removed from 6.x with the following upstream commit: https://github.com/elastic/elasticsearch/commit/9d8f11dc27c1fc2057e7ea5a82c0a5f364f5e8ce#diff-4a4d0518983ac4a587c14d372df2e241, which is a problem because https://github.com/elastic/puppet-elasticsearch/blob/1e37380d8ec69c579ad2d7fcf0dbb45c064e77b1/files/etc/init.d/elasticsearch.systemd.erb#L15

tries to run it.

It was simple enough to create a minimal noop executable file but hopefully this saves 6.x testers some time wondering why ES isn't starting. 😃

**Comment by tylerjl** [comment]
@dfwarden the systemd service unit should actually still work fine without that file present since `ExecStartPre=` is prefixed with the minus sign `-` [which indicates that the daemon should startup even if the exe fails to run](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=). Travis runs acceptance tests against snapshot builds of Elasticsearch (which is at 6.0.0-beta2 right now, I believe) and they all pass, so are you seeing actual failures to start in your environment, or just messages indicating that the file is not present, but ES still starts fine?

**Comment by dfwarden** [comment]
Ah, I'm sorry for this noise. I looked closer and saw there were additional failures (xpack ssl then a permissions failure on the instance scripts symlink) that I didn't realize were happening because no logs were going to path.logs in my instance elasticsearch.yml. (I poked around a bit more and found "${sys:es.logs}.log" in /usr/share/elasticsearch, so I must have some part of the logging config wrong.)

**Comment by tylerjl** [comment]
No worries, I appreciate the inclination to let us know about potential problems! 👍
