### ISSUE TITLE
Unit tests on Fedora

### ISSUE THREAD

**Issue by lukebigum** [elastic/puppet-elasticsearch#903]
* Module version: master
* Puppet version: 4.10
* OS and version: Fedora

## Bug description

There are Ubuntu-like hard coded paths in some provider unit tests relating to the defaults directory:

```
  3) Puppet::Type::Elasticsearch_keystore::ProviderElasticsearch_keystore instances with one instance instance es-01 should receive execute(["/usr/share/elasticsearch/bin/elasticsearch-keystore", "list"], {:custom_environment=>{"ES_INCLUDE"=>"/etc/default/elasticsearch-es-01", "ES_PATH_CONF"=>"/etc/elasticsearch/es-01"}, :uid=>"elasticsearch", :gid=>"elasticsearch"}) 1 time
     Failure/Error: stdout = execute([command(:keystore)] + args, options)
     
       #<Puppet::Type::Elasticsearch_keystore::ProviderElasticsearch_keystore (class)> received :execute with unexpected arguments
         expected: (["/usr/share/elasticsearch/bin/elasticsearch-keystore", "list"], {:custom_environment=>{"ES_INCLUDE"=>"/etc/default/elasticsearch-es-01", "ES_PATH_CONF"=>"/etc/elasticsearch/es-01"}, :uid=>"elasticsearch", :gid=>"elasticsearch"})
              got: (["/usr/share/elasticsearch/bin/elasticsearch-keystore", "list"], {:custom_environment=>{"ES_INCLUDE"=>"/etc/sysconfig/elasticsearch-es-01", "ES_PATH_CONF"=>"/etc/elasticsearch/es-01"}, :uid=>"elasticsearch", :gid=>"elasticsearch"})
       Diff:
       @@ -1,6 +1,6 @@
        [["/usr/share/elasticsearch/bin/elasticsearch-keystore", "list"],
         {:custom_environment=>
       -   {"ES_INCLUDE"=>"/etc/default/elasticsearch-es-01",
       +   {"ES_INCLUDE"=>"/etc/sysconfig/elasticsearch-es-01",
            "ES_PATH_CONF"=>"/etc/elasticsearch/es-01"},
          :uid=>"elasticsearch",
          :gid=>"elasticsearch"}]
```

I can see that some of the class unit tests switch the value of the symbol _:defaults_path_ in a `on_supported_os.each` loop, but I'm not sure the best way to get this down into provider units tests (or if it's even possible).

Maybe there's a way to pull the _osfamily_ Fact from inside a unit test then switch on the expected value?

**Comment by tylerjl** [comment]
@lukebigum yeah, I think trying to use the `on_supported_os` loop is probably the best initial approach to try and get those working. Since Fedora isn't technically on the [support matrix](https://www.elastic.co/support/matrix) for Elasticsearch this one isn't a _high_ priority for me, but I'd be happy to merge any PRs that address this. 👍

**Comment by lukebigum** [comment]
s/Fedora/RedHat/ :-)  I had a quick attempt at trying, but because the provider tests are Pure rspec and not Puppet rspec there's no such thing as `on_supported_os`.  Maybe I can stub the Facts somehow, I'll take a look.

**Comment by tylerjl** [comment]
Hey @lukebigum, I recently tried to run the unit tests on a Fedora machine of mine and finally grokked what this issue is all about, I added 8f299b3b75137129c02a606066da60d178ba8600 to `master` and it looks like all the tests should be host-distro agnostic now (all the tests passed on my Fedora setup), so I think this is solved. The solution isn't 100% pretty but at least we can control it and have insulated the tests from whatever the platform the host is.

Please do raise any concerns if this doesn't happen to solve it for you.
