### ISSUE TITLE
Systemd - ExecStartPre command doesn't exist anymore

### ISSUE THREAD

**Issue by tdegiacinto** [elastic/puppet-elasticsearch#918]
Hello,

Not sure if I'm the only one facing this situation but I wasn't able to start Elasticsearch service due to the fact that "/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec" doesn't exist in last ubuntu packages.

Env: 
OS : Ubuntu 16.04
Elasticsearch package version : 6.1.1

I guess we need to remove `ExecStartPre=-/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec` from the systemd template file

Regards

Thomas

**Comment by tylerjl** [comment]
Hi @tdegiacinto, because `ExecStartPre=-` contains a trailing minus sign, the systemd service script will start regardless of whether that file exists or not, so your issue is likely something else.

However, this red herring has caused way too much confusion for users so I'll use this issue to track removing the `ExecStartPre=-` line from the systemd service file. It mostly served as an alert to notify users about `CONF_FILE` deprecation, which doesn't exist anywhere in this module anyway (and is actually explicitly removed).

**Comment by tdegiacinto** [comment]
Okay thanks I wasn't aware about the particularity of the minus sign.

**Comment by tylerjl** [comment]
Closed in #919
