### ISSUE TITLE
Regression? Could not autoload puppet/provider/elasticsearch_plugin/elasticsearch_plugin

### ISSUE THREAD

**Issue by nick-george** [elastic/puppet-elasticsearch#933]
Hi, 

I'm having an issue that has been seen before with this module. I wasn't sure if I should re-open the issue or just create a new one. 

* Module version: 6.2.2
* Puppet Server version 2.8.1-1 (PC1)
* Puppet Agent version: 4.10.11
* OS and version: Oracle Linux Server release 7.5

I'm consistently seeing the following error on my puppet agents. I'm not running the latest version, but I believe I'm running the latest PC1 version of puppet (the most supported version?). 

> Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Override, Could not autoload puppet/type/elasticsearch_plugin: Could not autoload puppet/provider/elasticsearch_plugin/elasticsearch_plugin: no such file to load -- puppet/provider/elastic_plugin at /etc/puppetlabs/code/environments/development/modules/elasticsearch/manifests/plugin.pp:94:5

I seem to remember that this issue had something to do with running directory environments in Puppet. I'm most certainly doing that, but running the same version of this module across all my environments. If I restart the puppetserver service on the master and immediately run the agent, I seem to be able to get some success. 

Do you have any suggestions on how I can fix this? 

Many thanks, 
Nick George

**Comment by tylerjl** [comment]
So the stock answer I have for this (which I have saved as a GitHub issue response, hah!) is:

> This is a common problem when updating a module that changes parameters for a native provider (see [the upstream Puppet Labs issue](https://tickets.puppetlabs.com/browse/SERVER-94)). Please try restarting the puppetmaster (and potentially any effected puppet agents) and try re-running puppet again.

The unfortunate reality (and why I link directly to the upstream Puppet issue tracker) is that this seems endemic to Puppet. I usually observe problems when a native provider is updated or otherwise changes which seems to trigger the behavior as well. The most reliable remediation _seems_ to be restarting either the master or agent, as you mention.

I checked that Jira issue and although Puppet labs has marked it as "closed", the final comments certainly imply that workarounds are still necessary. I wish I had a better answer, but there's little (if any) action I can take on the module side to help mitigate the problem.

**Comment by nick-george** [comment]
Thanks for your quick response Tyler, 

The odd thing is that sometimes I restart the puppetserver service and the same issue crops up immediately. I've pushed version 6.2.2 of this module out to all of my environments and it has been that way for quite some time, I can't think of how the native provider would be changing. It's a pretty frustrating issue as it causes the entire agent run to bail. 

I appreciate the time you took to write a detailed response!

Cheers, 
Nick

**Comment by tylerjl** [comment]
No worries, I'm sorry there isn't a better answer here. I've looked into whether I could do things like try and determine if any native types/providers would trigger a new pluginsync/etc. to try and provide helpful output, but haven't found many options, unfortunately.

Is there anything else that needs resolution here, or are you ready to close?

**Comment by nick-george** [comment]
All good. Ready to close. Thanks for the detail.

**Comment by walkamongus** [comment]
FYI I ran into this exact issue on Puppet 5.5.6 on module v 6.2.2 even with all steps taken to provide environment isolation (https://puppet.com/docs/puppet/5.5/environment_isolation.html).

Specifically my Puppetsever logs were bailing on https://github.com/elastic/puppet-elasticsearch/blob/6.2.2/manifests/plugin.pp#L94. The only way I can reliably work around the issue is to set `restart_plugin_change => false` in order to skip the resource default/plusignment operator that seems to be causing the issue.
